/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as StockRouteImport } from './routes/stock'
import { Route as ChallansIndexRouteImport } from './routes/challans.index'
import { Route as ChallansChallanIdRouteImport } from './routes/challans.$challanId'
import { Route as ChallansNewRouteImport } from './routes/challans.new'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers.$customerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallansIndexRoute = ChallansIndexRouteImport.update({
  id: '/challans/',
  path: '/challans/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallansChallanIdRoute = ChallansChallanIdRouteImport.update({
  id: '/challans/$challanId',
  path: '/challans/$challanId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallansNewRoute = ChallansNewRouteImport.update({
  id: '/challans/new',
  path: '/challans/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/invoices': typeof InvoicesRoute
  '/products': typeof ProductsRoute
  '/stock': typeof StockRoute
  '/challans/$challanId': typeof ChallansChallanIdRoute
  '/challans/new': typeof ChallansNewRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/challans/': typeof ChallansIndexRoute
  '/customers/': typeof CustomersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/invoices': typeof InvoicesRoute
  '/products': typeof ProductsRoute
  '/stock': typeof StockRoute
  '/challans/$challanId': typeof ChallansChallanIdRoute
  '/challans/new': typeof ChallansNewRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/challans': typeof ChallansIndexRoute
  '/customers': typeof CustomersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/invoices': typeof InvoicesRoute
  '/products': typeof ProductsRoute
  '/stock': typeof StockRoute
  '/challans/$challanId': typeof ChallansChallanIdRoute
  '/challans/new': typeof ChallansNewRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/challans/': typeof ChallansIndexRoute
  '/customers/': typeof CustomersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/invoices'
    | '/products'
    | '/stock'
    | '/challans/$challanId'
    | '/challans/new'
    | '/customers/$customerId'
    | '/challans/'
    | '/customers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/invoices'
    | '/products'
    | '/stock'
    | '/challans/$challanId'
    | '/challans/new'
    | '/customers/$customerId'
    | '/challans'
    | '/customers'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/invoices'
    | '/products'
    | '/stock'
    | '/challans/$challanId'
    | '/challans/new'
    | '/customers/$customerId'
    | '/challans/'
    | '/customers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  InvoicesRoute: typeof InvoicesRoute
  ProductsRoute: typeof ProductsRoute
  StockRoute: typeof StockRoute
  ChallansChallanIdRoute: typeof ChallansChallanIdRoute
  ChallansNewRoute: typeof ChallansNewRoute
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
  ChallansIndexRoute: typeof ChallansIndexRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challans/': {
      id: '/challans/'
      path: '/challans'
      fullPath: '/challans/'
      preLoaderRoute: typeof ChallansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challans/$challanId': {
      id: '/challans/$challanId'
      path: '/challans/$challanId'
      fullPath: '/challans/$challanId'
      preLoaderRoute: typeof ChallansChallanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challans/new': {
      id: '/challans/new'
      path: '/challans/new'
      fullPath: '/challans/new'
      preLoaderRoute: typeof ChallansNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  InvoicesRoute: InvoicesRoute,
  ProductsRoute: ProductsRoute,
  StockRoute: StockRoute,
  ChallansChallanIdRoute: ChallansChallanIdRoute,
  ChallansNewRoute: ChallansNewRoute,
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
  ChallansIndexRoute: ChallansIndexRoute,
  CustomersIndexRoute: CustomersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
